language: c

env:
  - BUILD_DIR=.

services:
  - docker

before_install:
  - docker build -t amary/softether-vpn-client $BUILD_DIR

install: true

script:
  - docker run amary/softether-vpn-client echo "[Travis CI OK]"
