language: c

env:
  - BUILD_DIR=.

services:
  - docker

before_install:
  - docker build -t amary/softether-vpn-bridge $BUILD_DIR

install: true

script:
  - docker run amary/softether-vpn-bridge echo "[Travis CI OK]"
